-- ==========================================
-- INSERÇÃO DOS TERRITÓRIOS
-- ==========================================
INSERT INTO Territorio (nome) VALUES
    ('O Norte'),
    ('Ilhas de Ferro'),
    ('Terras Fluviais'),
    ('Vale de Arryn'),
    ('Terras Ocidentais'),
    ('Terras da Coroa'),
    ('Campina'),
    ('Terras da Tempestade'),
    ('Dorne');

-- ==========================================
-- CASAS DO NORTE
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Bolton de Forte do Pavor', 1),
    ('Cerwyn', 1),
    ('Dustin', 1),
    ('Flint de Atalaia da Viúva', 1),
    ('Flint do Dedo de Pederneira', 1),
    ('Hornwood', 1),
    ('Karstark', 1),
    ('Locke', 1),
    ('Manderly', 1),
    ('Mormont', 1),
    ('Reed', 1),
    ('Ryswell', 1),
    ('Umber', 1),
    ('Glover', 1),
    ('Tallhart', 1),
    ('Ashwood', 1),
    ('Barbarruiva', 1),
    ('Bole', 1),
    ('Branch', 1),
    ('Branfield', 1),
    ('Cassel', 1),
    ('Condon', 1),
    ('Forrester', 1),
    ('Holt', 1),
    ('Ironsmith', 1),
    ('Lake', 1),
    ('Lightfoot', 1),
    ('Long', 1),
    ('Marsh', 1),
    ('Mollen', 1),
    ('Moss', 1),
    ('Overton', 1),
    ('Poole', 1),
    ('Slate', 1),
    ('Stout', 1),
    ('Thenn', 1),
    ('Waterman', 1),
    ('Wells', 1),
    ('Whitehill', 1),
    ('Woods', 1),
    ('Woolfield', 1),
    ('Burley', 1),
    ('Flint da Montanha da Pedra Partida', 1),
    ('Harclay', 1),
    ('Knott', 1),
    ('Liddle', 1),
    ('Norrey', 1),
    ('Wull', 1),
    ('Blackmyre', 1),
    ('Boggs', 1),
    ('Cray', 1),
    ('Fenn', 1),
    ('Greengood', 1),
    ('Peat', 1),
    ('Quagg', 1),
    ('Crowl', 1),
    ('Magnar', 1),
    ('Stane', 1),
    ('Amber', 1),
    ('Fisher da Costa Pedregosa', 1),
    ('Frost', 1),
    ('Greenwood', 1),
    ('Greystark', 1),
    ('Ryder', 1),
    ('Towers', 1),
    ('Woodfoot', 1),
    ('Stark', 1);

-- ==========================================
-- CASAS DAS ILHAS DE FERRO
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Greyjoy de Pyke', 2),
    ('Blacktyde', 2),
    ('Botley', 2),
    ('Drumm', 2),
    ('Farwynd de Ponta de Pelefoca', 2),
    ('Goodbrother de Cornartelo', 2),
    ('Goodbrother de Pedrasmagada', 2),
    ('Goodbrother de Montrasgo', 2),
    ('Harlaw', 2),
    ('Kenning', 2),
    ('Merlyn', 2),
    ('Myre', 2),
    ('Orkwood', 2),
    ('Saltcliffe', 2),
    ('Sparr', 2),
    ('Stonehouse', 2),
    ('Stonetree', 2),
    ('Sunderly', 2),
    ('Tawney', 2),
    ('Volmark', 2),
    ('Wynch', 2),
    ('Codd', 2),
    ('Farwynd da Luz Solitária', 2),
    ('Goodbrother de Lago do Cadáver', 2),
    ('Goodbrother de Forte do Espigão do Corvo', 2),
    ('Goodbrother de Covabaixa', 2),
    ('Harlaw de Jardim Cinzento', 2),
    ('Harlaw de Monte da Bruxa', 2),
    ('Harlaw de Solar de Harlaw', 2),
    ('Harlaw de Torre Bruxuleante', 2),
    ('Humble', 2),
    ('Ironmaker', 2),
    ('Netley', 2),
    ('Sharp', 2),
    ('Shepherd', 2),
    ('Weaver', 2),
    ('Greyiron', 2),
    ('Hoare', 2);

-- ==========================================
-- CASAS DAS TERRAS FLUVIAIS
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Baelish de Harrenhal', 3),
    ('Blackwood', 3),
    ('Bracken', 3),
    ('Butterwell', 3),
    ('Chambers', 3),
    ('Charlton', 3),
    ('Deddings', 3),
    ('Frey das Gêmeas', 3),
    ('Frey de Correrrio', 3),
    ('Goodbrook', 3),
    ('Grell', 3),
    ('Harlton', 3),
    ('Hawick', 3),
    ('Keath', 3),
    ('Lannister de Darry', 3),
    ('Lolliston', 3),
    ('Lychester', 3),
    ('Mallister', 3),
    ('Mooton', 3),
    ('Penny', 3),
    ('Piper', 3),
    ('Roote', 3),
    ('Ryger', 3),
    ('Shawney', 3),
    ('Smallwood', 3),
    ('Terrick', 3),
    ('Vance de Atranta', 3),
    ('Vance de Pouso do Viajante', 3),
    ('Vypren', 3),
    ('Wayn', 3),
    ('Blanetree', 3),
    ('Cox', 3),
    ('Erenford', 3),
    ('Haigh', 3),
    ('Nayland', 3),
    ('Paege', 3),
    ('Wode', 3),
    ('Bigglestone', 3),
    ('Darry', 3),
    ('Fisher', 3),
    ('Grey', 3),
    ('Harroway', 3),
    ('Hoare', 3),
    ('Hook', 3),
    ('Justman', 3),
    ('Nutt', 3),
    ('Perryn', 3),
    ('Qoherys', 3),
    ('Teague', 3),
    ('Towers', 3),
    ('Whent', 3),
    ('Lothston', 3),
    ('Mudd', 3),
    ('Strong', 3),
    ('Tully', 3);


-- ==========================================
-- CASAS DO VALE DE ARRYN
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Arryn do Ninho da Águia', 4),
    ('Belmore', 4),
    ('Breakstone', 4),
    ('Coldwater', 4),
    ('Corbray', 4),
    ('Donniger', 4),
    ('Egen', 4),
    ('Elesham', 4),
    ('Grafton', 4),
    ('Hardyng', 4),
    ('Hersy', 4),
    ('Hunter', 4),
    ('Lynderly', 4),
    ('Melcolm', 4),
    ('Moore', 4),
    ('Pryor', 4),
    ('Redfort', 4),
    ('Royce de Pedrarruna', 4),
    ('Royce dos Portões da Lua', 4),
    ('Ruthermont', 4),
    ('Tollett', 4),
    ('Upcliff', 4),
    ('Waynwood', 4),
    ('Wydman', 4),
    ('Shett de Torre das Gaivotas', 4),
    ('Shett de Vila Gaivota', 4),
    ('Templeton', 4),
    ('Waxley', 4),
    ('Borrell', 4),
    ('Longthorpe', 4),
    ('Sunderland', 4),
    ('Torrent', 4),
    ('Arryn de Vila Gaivota', 4),
    ('Baelish dos Dedos', 4),
    ('Cães Pintados', 4),
    ('Corvos de Pedra', 4),
    ('Ferreiros Vermelhos', 4),
    ('Filhos da Árvore', 4),
    ('Filhos da Névoa', 4),
    ('Homens Queimados', 4),
    ('Irmãos da Lua', 4),
    ('Orelhas Negras', 4),
    ('Serpentes de Leite', 4),
    ('Uivadores', 4),
    ('Brightstone', 4),
    ('Shell', 4);

-- ==========================================
-- CASAS DAS TERRAS OCIDENTAIS
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Lannister do Rochedo Casterly', 5),
    ('Algood', 5),
    ('Banefort', 5),
    ('Bettley', 5),
    ('Brax', 5),
    ('Broom', 5),
    ('Crakehall', 5),
    ('Doggett', 5),
    ('Drox', 5),
    ('Estren', 5),
    ('Falwell', 5),
    ('Farman', 5),
    ('Ferren', 5),
    ('Foote', 5),
    ('Garner', 5),
    ('Hamell', 5),
    ('Hawthorne', 5),
    ('Jast', 5),
    ('Kenning', 5),
    ('Kyndall', 5),
    ('Lannister de Lannisporto', 5),
    ('Lefford', 5),
    ('Lydden', 5),
    ('Marbrand', 5),
    ('Moreland', 5),
    ('Myatt', 5),
    ('Payne', 5),
    ('Peckledon', 5),
    ('Plumm', 5),
    ('Prester', 5),
    ('Sarsfield', 5),
    ('Sarwyck', 5),
    ('Serrett', 5),
    ('Spicer', 5),
    ('Stackspear', 5),
    ('Turnberry', 5),
    ('Westerling', 5),
    ('Westford', 5),
    ('Yarwyck', 5),
    ('Clifton', 5),
    ('Greenfield', 5),
    ('Hetherspoon', 5),
    ('Lorch', 5),
    ('Ruttiger', 5),
    ('Swyft', 5),
    ('Vikary', 5),
    ('Yew', 5),
    ('Casterly', 5),
    ('Clegane', 5),
    ('Parren', 5),
    ('Reyne', 5),
    ('Tarbeck', 5);

-- ==========================================
-- CASAS DAS TERRAS DA COROA
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Baratheon de Porto Real', 6),
    ('Belgrave', 6),
    ('Blackberry', 6),
    ('Blount', 6),
    ('Buckwell', 6),
    ('Byrch', 6),
    ('Bywater', 6),
    ('Chelsted', 6),
    ('Chyttering', 6),
    ('Cressey', 6),
    ('Edgerton', 6),
    ('Farring', 6),
    ('Follard', 6),
    ('Gaunt', 6),
    ('Goode', 6),
    ('Harte', 6),
    ('Hayford', 6),
    ('Langward', 6),
    ('Mallery', 6),
    ('Manning', 6),
    ('Massey', 6),
    ('Pyle', 6),
    ('Rollingford', 6),
    ('Rosby', 6),
    ('Rykker', 6),
    ('Slynt', 6),
    ('Staunton', 6),
    ('Stokeworth', 6),
    ('Sweet', 6),
    ('Thorne', 6),
    ('Wendwater', 6),
    ('Brune de Antro Terrível', 6),
    ('Hogg', 6),
    ('Kettleblack', 6),
    ('Baratheon da Pedra do Dragão', 6),
    ('Bar Emmon', 6),
    ('Celtigar', 6),
    ('Rambton', 6),
    ('Sunglass', 6),
    ('Velaryon', 6),
    ('Boggs', 6),
    ('Brune de Cova Castanha', 6),
    ('Cave', 6),
    ('Crabb', 6),
    ('Hardy', 6),
    ('Pyne', 6),
    ('Dargood', 6),
    ('Darke', 6),
    ('Darkwood', 6),
    ('Leek', 6),
    ('Longwaters', 6),
    ('Suggs', 6),
    ('Blackfyre', 6),
    ('Cargyll', 6),
    ('Darklyn', 6),
    ('Hollard', 6),
    ('Mandrake', 6),
    ('Targaryen', 6);

-- ==========================================
-- CASAS DA CAMPINA
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Tyrell de Jardim de Cima', 7),
    ('Appleton', 7),
    ('Ambrose', 7),
    ('Ashford', 7),
    ('Beesbury', 7),
    ('Blackbar', 7),
    ('Bulwer', 7),
    ('Caswell', 7),
    ('Cockshaw', 7),
    ('Cordwayner', 7),
    ('Costayne', 7),
    ('Crane', 7),
    ('Cupps', 7),
    ('Cuy', 7),
    ('Hightower', 7),
    ('Meadows', 7),
    ('Merryweather', 7),
    ('Mullendore', 7),
    ('Oakheart', 7),
    ('Peake', 7),
    ('Redwyne', 7),
    ('Rowan', 7),
    ('Shermer', 7),
    ('Tarly', 7),
    ('Tyrell de Águas Claras', 7),
    ('Varner', 7),
    ('Vyrwel', 7),
    ('Chester', 7),
    ('Grimm', 7),
    ('Hewett', 7),
    ('Serry', 7),
    ('Ball', 7),
    ('Bridges', 7),
    ('Bushy', 7),
    ('Conklyn', 7),
    ('Dunn', 7),
    ('Durwell', 7),
    ('Farrow', 7),
    ('Footly', 7),
    ('Fossoway de Solar de Sidra', 7),
    ('Graceford', 7),
    ('Graves', 7),
    ('Greenhill', 7),
    ('Hastwyck', 7),
    ('Hunt', 7),
    ('Hutcheson', 7),
    ('Inchfield', 7),
    ('Kidwell', 7),
    ('Leygood', 7),
    ('Lowther', 7),
    ('Lyberr', 7),
    ('Middlebury', 7),
    ('Norcross', 7),
    ('Norridge', 7),
    ('Oldflowers', 7),
    ('Orme', 7),
    ('Pommingham', 7),
    ('Potter', 7),
    ('Redding', 7),
    ('Rhysling', 7),
    ('Risley', 7),
    ('Roxton', 7),
    ('Sawyer', 7),
    ('Sloane', 7),
    ('Stackhouse', 7),
    ('Uffering', 7),
    ('Webber', 7),
    ('Westbrook', 7),
    ('Willum', 7),
    ('Woodwright', 7),
    ('Wythers', 7),
    ('Yelshire', 7),
    ('Fossoway de Novo Barril', 7),
    ('Osgrey de Pousoveloz', 7),
    ('Gardener', 7),
    ('Osgrey de Lago Frondoso', 7),
    ('Florent', 7),
    ('Strickland', 7);


-- ==========================================
-- CASAS DAS TERRAS DA TEMPESTADE
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Baratheon de Ponta Tempestade', 8),
    ('Dondarrion', 8),
    ('Foote de Nocticantiga', 8),
    ('Swann', 8),
    ('Bolling', 8),
    ('Buckler', 8),
    ('Cafferen', 8),
    ('Errol', 8),
    ('Estermont', 8),
    ('Fell', 8),
    ('Gower', 8),
    ('Grandison', 8),
    ('Hasty', 8),
    ('Herston', 8),
    ('Horpe', 8),
    ('Kellington', 8),
    ('Lonmouth', 8),
    ('Mertyns', 8),
    ('Morrigen', 8),
    ('Musgood', 8),
    ('Peasebury', 8),
    ('Penrose', 8),
    ('Rogers', 8),
    ('Staedmon', 8),
    ('Swygert', 8),
    ('Tarth', 8),
    ('Trant', 8),
    ('Tudbury', 8),
    ('Wagstaff', 8),
    ('Wensington', 8),
    ('Wylde', 8),
    ('Connington', 8),
    ('Seaworth', 8),
    ('Selmy', 8),
    ('Cole', 8),
    ('Caron', 8),
    ('Durrandon', 8),
    ('Toyne', 8);

-- ==========================================
-- CASAS DE DORNE
-- ==========================================
INSERT INTO Casas (nome, territorio_id) VALUES
    ('Martell de Lançassolar', 9),
    ('Allyrion', 9),
    ('Blackmont', 9),
    ('Dayne de Tombastela', 9),
    ('Fowler', 9),
    ('Gargalen', 9),
    ('Jordayne', 9),
    ('Ladybright', 9),
    ('Manwoody', 9),
    ('Qorgyle', 9),
    ('Toland', 9),
    ('Uller', 9),
    ('Vaith', 9),
    ('Wyl', 9),
    ('Yronwood', 9),
    ('Dalt', 9),
    ('Dayne de Alto Ermitério', 9),
    ('Drinkwater', 9),
    ('Santagar', 9),
    ('Wells', 9),
    ('Briar', 9),
    ('Brook', 9),
    ('Brownhill', 9),
    ('Dryland', 9),
    ('Holt', 9),
    ('Hull', 9),
    ('Lake', 9),
    ('Shell', 9),
    ('Wade', 9);

-- ==========================================
-- FIM DOS INSERTS
-- ==========================================


